## We are doing a data analysis task for patients to study their inglammattion as per a new treatment for Arthiritis

Data is in CSV format

Data description
- Each row has information for a single patient
- Each column represents successive days of the clinical study
- Each number represents the no. of inflammation bouts that a particular patient experienced on a given day

Dummy Data

0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0
0,1,2,1,2,1,3,2,2,6,10,11,5,9,4,4,7,16,8,6,18,4,12,5,12,7,11,5,11,3,3,5,4,4,5,5,1,1,0,1
0,1,1,3,3,2,6,2,5,9,5,7,4,5,4,15,5,11,9,10,19,14,12,17,7,12,11,7,4,2,10,5,4,2,2,3,2,2,1,1

###### Final Task
- Calculate average inflammation per day accross all patients
- Plot results

### Python Fundamentals

In [20]:
#Arthemetics

3+5*3

18

In [21]:
#Assigning the value to a variable. 
a=60

Variable names can have alphanumerics and underscores. They can't start with a number and are case sensitive

3 common data types are
- integers [a=60]
- floating point numbers or decimals [a=60.0]
- strings [a='is a variable'] or [a="is a variable"]


In [22]:
#Printing the value of the variable
print(a)

#printing multiple variables
b="my variable's value is "
print (b,a)

#printing string and a variable
print("my variable's value is ",a)

#arithmetic in print function
print("10 added to my variable is ", a+10)

60
my variable's value is  60
my variable's value is  60
10 added to my variable is  70


In [23]:
#Python has a self decration, so the variable type gets 
#decared based on the type of value it holds at the ti,e of initialization (as below)
# b="a"
# b=b*1.5
# print(b)

In [24]:
#Also, there are some errors in calcuation from FPU
a=6
a=a*2.1
print(a)

12.600000000000001


In actual terms, variable is a place in memory. It has a certain memory address and a name associated with it. The variable a refers to an address in the memory which holds n bytes of information. This number n is defined by the data type it holds and the way data is stored using python.

In [25]:
#small question
mass=47.5
age=122
mass=mass*2.0
age=age-20

#Then the value of mass is updated and is equal to its initial value multiplied by 2
#Similarly, the value of age is updated and is equal to its initial value minus 20
print(mass)
print(age)

#We can also print the datatype of the varable by the Python (in-built) function type() {takes the argument variable and returns the data type of the variable}
print(type(mass))

95.0
102
<class 'float'>


In [26]:
#Assignment of 2 variables in one command
first, second= 'Grace', 'Hopper'
third, fourth=second, first
print(third, fourth)

Hopper Grace


### Analyzing Patients Data

We'll be using a library called NumPy (Python library for Numerical Analysis)

Libraries are collections of functions and constructs that can be used in Python to carry out the required tasks. These add modularity to Python. Numpy library has functions and data types for making numerical analysis easier. For example, Numpy arrays are a data-type which stores data as matrices which makes matrix calculations easy and faster (by optimizing it).

In [27]:
#To install numpy, use-
#!pip install numpy
#Here, ! is used to specify that the command is supposed to be run in 
#the terminal directly.

In [28]:
#Once installed (or if already installed), import the library in the current workspace
import numpy as np
#np is an alias for numpy (can be anything with naming convention similar to variables)

In [29]:
#Load a csv data (inflammation-01.csv). We can also use fname='data/...' 
#in the function loadtxt, however, the function by default takes the first argument as the
#file location
np.loadtxt('data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

A function is a block of code that takes the arguments/parameters specified in the brackets () as inputs to the function, executes the code written in the function and typically returns an output.

np.loadtxt() calls the function from the library numpy. It has 2 parameters
- The name of the file (fname) - String input
- The delimiter that separates different values on one line - String input

In [30]:
#We can use ? (in beginning or the end) or help() function in order to get an explanation of any function from the documentation
?np.loadtxt

Signature:
np.loadtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    converters=None,
    skiprows=0,
    usecols=None,
    unpack=False,
    ndmin=0,
    encoding='bytes',
    max_rows=None,
)
Docstring:
Load data from a text file.

Each row in the text file must have the same number of values.

Parameters
----------
fname : file, str, or pathlib.Path
    File, filename, or generator to read.  If the filename extension is
    ``.gz`` or ``.bz2``, the file is first decompressed. Note that
    generators should return byte strings.
dtype : data-type, optional
    Data-type of the resulting array; default: float.  If this is a
    structured data-type, the resulting array will be 1-dimensional, and
    each row will be interpreted as an element of the array.  In this
    case, the number of columns used must match the number of fields in
    the data-type.
comments : str or sequence of str, optional
    The characters or list of characters used to indica

In [31]:
#Assign the loaded data into a variable
data=np.loadtxt('data/inflammation-01.csv', delimiter=',')
print("Values present in data variable: ", data)
#type(variable_name) function takes a variable as the parameter and returns its datatype
#Here, our variable is of the data type N-dimensional NumPy array
print("Data Type of the variable: ", type(data))
#The attribute .dtype for a variable tells the data-type of elements of the array
print("Elements' data type: ", data.dtype)
#The attribute .shape tells the dimensional lengths of the numpy array, thereby, it's shape
print("Array shape: ", data.shape)

Values present in data variable:  [[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
Data Type of the variable:  <class 'numpy.ndarray'>
Elements' data type:  float64
Array shape:  (60, 40)


The attributes or members are the metadata about the array

In [32]:
#Getting a single element from the array, we can use [] to specify exact variable indexes
#for the array elements we need
#Since we have a 2D array, we will need 2 numbers to specify an element
#In Python, array indexing starts with 0 - as this notation represnts an offset from the first value of the array
#So, the first element is indexed at [0][0]
#The rows move down from the first number while the columns move with the second number
print("First Element of first row is: ", data[0][0])
print("First Element of fifth row is: ", data[0][4])
print("Fifth Element of first row is: ", data[4][0])
print("Middle value in data is: ", data[30][20])

First Element of first row is:  0.0
First Element of fifth row is:  1.0
Fifth Element of first row is:  0.0
Middle value in data is:  13.0


In [33]:
#We can slice data (take a portion of the data)
#A section of an array is called a slice
print("First five full rows of the data:\n", data[0:4])
print("10 elements each from rows 5 to 10:\n", data[4:9, 0:10])
#Open cloumns mean from start :n (by default 0 to the nth element) or from n to the end n: (till the last element of that particular dimension) 
print("all rows after 50th row and all columns till 7th coloumn for these rows:\n", data[49:,:6])

First five full rows of the data:
 [[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
  12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
   2.  3.  0.  0.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10. 19. 14. 12. 17.  7. 12. 11.  7.  4.  2. 10.  5.  4.  2.  2.  3.
   2.  2.  1.  1.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7. 10.  7.  9. 13.  8.  8. 15. 10.
  10.  7. 17.  4.  4.  7.  6. 15.  6.  4.  9. 11.  3.  5.  6.  3.  3.  4.
   2.  3.  2.  1.]]
10 elements each from rows 5 to 10:
 [[0. 1. 1. 3. 3. 1. 3. 5. 2. 4.]
 [0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]]
all rows after 50th row and all columns till 7th coloumn for these rows:
 [[0. 0. 1. 2. 3. 4.

In [34]:
#Side note
#Not all functions require an input argument. Parantheses are written to tell Python that we are calling a function with no inputs
#For example, the ctime() function of the package time tells the current time
import time
print("Current Date and Time: ", time.ctime())

Current Date and Time:  Tue Feb  2 17:42:25 2021


In [35]:
#NumPy analyzing functions
print("Mean or average of all elements of the data array, or the average inflammation counts for all patients over all days: ",np.mean(data))
print("Max value (Max number of infammations of any patient over all days): ", np.max(data))
print("Min value (Min number of infammations of any patient over all days): ", np.min(data))
print("Standard deviation of number of infammations of all patient over all days): ", np.std(data))

Mean or average of all elements of the data array, or the average inflammation counts for all patients over all days:  6.14875
Max value (Max number of infammations of any patient over all days):  20.0
Min value (Min number of infammations of any patient over all days):  0.0
Standard deviation of number of infammations of all patient over all days):  4.613833197118566


In [36]:
#Getting the maximum inflammations of a given patient
n=0
patient_n = data[n] #Can also be used as data[0,:] which indicates to pick the 0th row and every column
#print(patient_0)
if((n+1)>10 and (n+1)<20):
    th="th"
elif((n+1)%10==1):
    th="st" 
elif((n+1)%10==2):
    th="nd" 
elif((n+1)%10==3):
    th="rd" 
else:
    th="th"
print("Maximum inflammation of ",n+1, th," patient is: ",np.max(patient_n))
#Or
print("Minimum inflammation of ",n+1,"\bst patient is: ",np.min(data[n]))
#Here \b is the regular expression telling the print pointer to go Back by one character

Maximum inflammation of  1 st  patient is:  18.0
Minimum inflammation of  1st patient is:  0.0


In [54]:
?np.mean

Signature: np.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
Docstring:
Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a mean is performed over multiple axes,
    instead of a single axis or all the axes as before.
dtype : data-type, optional
    Type to use in computing the mean.  For integer inputs, the default
    is `float64`; for floating point inputs, it is the same as the
    input dtype.
ou

In [53]:
#What we need is
from IPython.display import HTML
HTML('<iframe width="800" height="450" src="https://swcarpentry.github.io/python-novice-inflammation/fig/python-operations-across-axes.png" frameborder="" style="background:#FFFFFF;"></iframe>')

In [68]:
#Mean across the 1st axis (across the patients)- This means that the first axis is locked and mean is calculated for values through the all values in second axis
print("The mean inflammations per day over all patients:\n", np.mean(data, axis=0))
print("Shape of data: ", data.shape)
print("Shape of resultant means: ", np.mean(data, axis=0).shape)

The mean inflammations per day over all patients:
 [ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]
Shape of data:  (60, 40)
Shape of resultant means:  (40,)


In [69]:
#Similarly
print("The mean inflammations per patient over all days:\n", np.mean(data, axis=1))
print("Shape of data: ", data.shape)
print("Shape of resultant means: ", np.mean(data, axis=1).shape)

The mean inflammations per patient over all days:
 [5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]
Shape of data:  (60, 40)
Shape of resultant means:  (60,)


#### More on Slicing


In [91]:
element='oxygen'
print("First 3 characters of element are: ", element[:3])
print("Last 3 characters are: ", element[3:6])
print("Number of characters in element name: ", len(element))
print("Last 3 characters of any element are: ", element[len(element)-3:len(element)])
print("First 4 characters of element are: ", element[:4]) #Exclusive of 4th element or 5th character of the string
print("all characters after 4th character of element are: ", element[4:]) #Inclusive of 4th element or 5th character of the string
print("all characters of element: ", element[:])
print("last characters of element: ", element[-1])
print("Second last characters of element: ", element[-2])
print("Last 3 characters of any element are: ", element[-3:]) #Alternative
print("Last, first and second characters of element are: ", element[-1:1]) #Creates a substring from index 1 up to (not including) the final index, effectively removing the first and last letters from ‘oxygen’

First 3 characters of element are:  oxy
Last 3 characters are:  gen
Number of characters in element name:  6
Last 3 characters of any element are:  gen
First 4 characters of element are:  oxyg
all characters after 4th character of element are:  en
all characters of element:  oxygen
last characters of element:  n
Second last characters of element:  e
Last 3 characters of any element are:  gen
Last, first and second characters of element are:  


In [100]:
#The following created empty arrays. This is called thin slice.
print(element[3:3]) #Empty string (with no characters) is created
print(data[3:3,4:4].shape) #Empty 2D array with no elements
print(data[3:3,:]) #Empty 2D array with 40 dimensions with empty characters
print(data[3:3,:].shape)


(0, 0)
[]
(0, 40)


In [114]:
#Stacking of arrays
A = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
print("A:\n", A)
#Horizontal stacking of arrays
B=np.hstack([A,A])
print("B:\n", B)
#Vertical Stacking of arrays
C=np.vstack([A,A])
print("C:\n",C)
#Shapes
print("Shapes\n", "A: ", A.shape, "\nB: ", B.shape, "\nC: ", C.shape)
#Dimensions (Still unchanged)
print("Dimension\n","A: ", A.ndim, "\nB: ", B.ndim, "\nC: ", C.ndim)

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B:
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C:
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
Shapes
 A:  (3, 3) 
B:  (3, 6) 
C:  (6, 3)
Dimension
 A:  2 
B:  2 
C:  2


In [143]:
print(A[:,0], A[:,-1], "\nShapes\n", A[:,0].shape, A[:,2].shape)
#^Here, singleton dimensions are dropped by default making these two 1-D arrays.
A_s=np.hstack((A[:, 0], A[:,-1]))
print("1D sliced and stacked A_s:\n", A_s)

#To preserve it as a 2D array (singleton dimensions), we use the following-
print("Preserved Singletons\n", A[:, :1], A[:,-1:], "\nShapes\n", A[:, :1].shape, A[:,-1:].shape)
A_s=np.hstack((A[:, :1], A[:,-1:]))
print("Final Sliced and Stacked A with first and last columns:\n", A_s)

##We can also use np.delete function to delete the second column
del_A=np.delete(A,1,1) #here, the first 1 is for the column (object to delete), while the second 1 is for the axis to delete along so as to prevent flattening of the resultant array
print("Deleted Column Array:\n", del_A)

[1 4 7] [3 6 9] 
Shapes
 (3,) (3,)
1D sliced and stacked A_s:
 [1 4 7 3 6 9]
Preserved Singletons
 [[1]
 [4]
 [7]] [[3]
 [6]
 [9]] 
Shapes
 (3, 1) (3, 1)
Final Sliced and Stacked A with first and last columns:
 [[1 3]
 [4 6]
 [7 9]]
Deleted Column Array:
 [[1 3]
 [4 6]
 [7 9]]


In [165]:
#np.diff() takes an array as an input and returns the differences between 2 successive values. The difference is calculated as data[i+1]-data[i] (next element - current element)
patient3_week1 =data[2, :7]
print("patient3_week1: ", patient3_week1, "\tshape: ", patient3_week1.shape)
print("patient3_week1 differences: ", np.diff(patient3_week1), "\tshape: ",np.diff(patient3_week1).shape)

#For multidimensional arrays, axis argument can be passed to tell which axis it is supposed to process
# print("Data 1st row ", data[1])
# print("Differences of all patients' week1 data directly through the multidimensional array: \n", np.diff(data[:,:7], axis=1), "\tshape: ", np.diff(data[:,:7], axis=1).shape)

#Getting largest differences between all days - Max of differences for all patients is calculated accross all days
#Absolute function is used to get the absolute of difference between days as in case the cases are decreasing accorss dats, the difference wi be negative
print(np.max(np.absolute(np.diff(data, axis=1)), axis=1)) 

patient3_week1:  [0. 1. 1. 3. 3. 2. 6.] 	shape:  (7,)
patient3_week1 differences:  [ 1.  0.  2.  0. -1.  4.] 	shape:  (6,)
Data 1st row  [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
  8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
  1.  1.  0.  1.]
Differences of all patients' week1 data directly through the multidimensional array: 
 [[ 0.  1.  2. -2.  1.  2.]
 [ 1.  1. -1.  1. -1.  2.]
 [ 1.  0.  2.  0. -1.  4.]
 [ 0.  2. -2.  4. -2.  0.]
 [ 1.  0.  2.  0. -2.  2.]
 [ 0.  1.  1.  0.  2. -2.]
 [ 0.  2.  0.  2. -2.  0.]
 [ 0.  1.  1.  1. -2.  1.]
 [ 0.  0.  3. -2.  4.  1.]
 [ 1.  0.  1. -1.  2.  2.]
 [ 1. -1.  0.  4. -1.  0.]
 [ 1. -1.  0.  3.  1. -2.]
 [ 0.  2. -1.  3. -1.  3.]
 [ 0.  0.  0.  1.  2. -2.]
 [ 1.  1. -1.  0.  0.  3.]
 [ 1.  0. -1.  1.  1.  2.]
 [ 0.  0.  0.  2.  1.  3.]
 [ 0.  0.  1.  1. -1.  3.]
 [ 0.  2. -1.  1.  3. -1.]
 [ 1.  1. -2.  1.  3. -1.]
 [ 1.  0.  2. -2.  3.  0.]
 [ 0.  2.  1. -1.  1. -1.]
 [ 0.  0.  3.  1. 