## We are doing a data analysis task for patients to study their inglammattion as per a new treatment for Arthiritis

Data is in CSV format

Data description
- Each row has information for a single patient
- Each column represents successive days of the clinical study
- Each number represents the no. of inflammation bouts that a particular patient experienced on a given day

Dummy Data

0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0
0,1,2,1,2,1,3,2,2,6,10,11,5,9,4,4,7,16,8,6,18,4,12,5,12,7,11,5,11,3,3,5,4,4,5,5,1,1,0,1
0,1,1,3,3,2,6,2,5,9,5,7,4,5,4,15,5,11,9,10,19,14,12,17,7,12,11,7,4,2,10,5,4,2,2,3,2,2,1,1

###### Final Task
- Calculate average inflammation per day accross all patients
- Plot results

### Python Fundamentals

In [35]:
#Arthemetics

3+5*3

18

In [36]:
#Assigning the value to a variable. 
a=60

Variable names can have alphanumerics and underscores. They can't start with a number and are case sensitive

3 common data types are
- integers [a=60]
- floating point numbers or decimals [a=60.0]
- strings [a='is a variable'] or [a="is a variable"]


In [37]:
#Printing the value of the variable
print(a)

#printing multiple variables
b="my variable's value is "
print (b,a)

#printing string and a variable
print("my variable's value is ",a)

#arithmetic in print function
print("10 added to my variable is ", a+10)

60
my variable's value is  60
my variable's value is  60
10 added to my variable is  70


In [38]:
#Python has a self decration, so the variable type gets 
#decared based on the type of value it holds at the ti,e of initialization (as below)
b="a"
b=b*1.5
print(b)

TypeError: can't multiply sequence by non-int of type 'float'

In [7]:
#Also, there are some errors in calcuation from FPU
a=6
a=a*2.1
print(a)

12.600000000000001


In actual terms, variable is a place in memory. It has a certain memory address and a name associated with it. The variable a refers to an address in the memory which holds n bytes of information. This number n is defined by the data type it holds and the way data is stored using python.

In [14]:
#small question
mass=47.5
age=122
mass=mass*2.0
age=age-20

#Then the value of mass is updated and is equal to its initial value multiplied by 2
#Similarly, the value of age is updated and is equal to its initial value minus 20
print(mass)
print(age)

#We can also print the datatype of the varable by the Python (in-built) function type() {takes the argument variable and returns the data type of the variable}
print(type(mass))

95.0
102
<class 'float'>


In [16]:
#Assignment of 2 variables in one command
first, second= 'Grace', 'Hopper'
third, fourth=second, first
print(third, fourth)

Hopper Grace


### Analyzing Patients Data

We'll be using a library called NumPy (Python library for Numerical Analysis)

Libraries are collections of functions and constructs that can be used in Python to carry out the required tasks. These add modularity to Python. Numpy library has functions and data types for making numerical analysis easier. For example, Numpy arrays are a data-type which stores data as matrices which makes matrix calculations easy and faster (by optimizing it).

In [17]:
#To install numpy, use-
#!pip install numpy
#Here, ! is used to specify that the command is supposed to be run in 
#the terminal directly.

In [18]:
#Once installed (or if already installed), import the library in the current workspace
import numpy as np
#np is an alias for numpy (can be anything with naming convention similar to variables)

In [19]:
#Load a csv data (inflammation-01.csv). We can also use fname='data/...' 
#in the function loadtxt, however, the function by default takes the first argument as the
#file location
np.loadtxt('data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

A function is a block of code that takes the arguments/parameters specified in the brackets () as inputs to the function, executes the code written in the function and typically returns an output.

np.loadtxt() calls the function from the library numpy. It has 2 parameters
- The name of the file (fname) - String input
- The delimiter that separates different values on one line - String input

In [20]:
#We can use ? (in beginning or the end) or help() function in order to get an explanation of any function from the documentation
?np.loadtxt

Signature:
np.loadtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    converters=None,
    skiprows=0,
    usecols=None,
    unpack=False,
    ndmin=0,
    encoding='bytes',
    max_rows=None,
)
Docstring:
Load data from a text file.

Each row in the text file must have the same number of values.

Parameters
----------
fname : file, str, or pathlib.Path
    File, filename, or generator to read.  If the filename extension is
    ``.gz`` or ``.bz2``, the file is first decompressed. Note that
    generators should return byte strings.
dtype : data-type, optional
    Data-type of the resulting array; default: float.  If this is a
    structured data-type, the resulting array will be 1-dimensional, and
    each row will be interpreted as an element of the array.  In this
    case, the number of columns used must match the number of fields in
    the data-type.
comments : str or sequence of str, optional
    The characters or list of characters used to indica

In [21]:
#Assign the loaded data into a variable
data=np.loadtxt('data/inflammation-01.csv', delimiter=',')
print("Values present in data variable: ", data)
#type(variable_name) function takes a variable as the parameter and returns its datatype
#Here, our variable is of the data type N-dimensional NumPy array
print("Data Type of the variable: ", type(data))
#The attribute .dtype for a variable tells the data-type of elements of the array
print("Elements' data type: ", data.dtype)
#The attribute .shape tells the dimensional lengths of the numpy array, thereby, it's shape
print("Array shape: ", data.shape)

Values present in data variable:  [[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
Data Type of the variable:  <class 'numpy.ndarray'>
Elements' data type:  float64
Array shape:  (60, 40)


The attributes or members are the metadata about the array

In [22]:
#Getting a single element from the array, we can use [] to specify exact variable indexes
#for the array elements we need
#Since we have a 2D array, we will need 2 numbers to specify an element
#In Python, array indexing starts with 0 - as this notation represnts an offset from the first value of the array
#So, the first element is indexed at [0][0]
#The rows move down from the first number while the columns move with the second number
print("First Element of first row is: ", data[0][0])
print("First Element of fifth row is: ", data[0][4])
print("Fifth Element of first row is: ", data[4][0])
print("Middle value in data is: ", data[30][20])

First Element of first row is:  0.0
First Element of fifth row is:  1.0
Fifth Element of first row is:  0.0
Middle value in data is:  13.0


In [29]:
#We can slice data (take a portion of the data)
print("First five full rows of the data:\n", data[0:4])
print("10 elements each from rows 5 to 10:\n", data[4:9, 0:10])
#Open cloumns mean from start :n (by default 0 to the nth element) or from n to the end n: (till the last element of that particular dimension) 
print("all rows after 50th row and all columns till 7th coloumn for these rows:\n", data[49:,:6])

First five full rows of the data:
 [[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
  12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
   2.  3.  0.  0.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10. 19. 14. 12. 17.  7. 12. 11.  7.  4.  2. 10.  5.  4.  2.  2.  3.
   2.  2.  1.  1.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7. 10.  7.  9. 13.  8.  8. 15. 10.
  10.  7. 17.  4.  4.  7.  6. 15.  6.  4.  9. 11.  3.  5.  6.  3.  3.  4.
   2.  3.  2.  1.]]
10 elements each from rows 5 to 10:
 [[0. 1. 1. 3. 3. 1. 3. 5. 2. 4.]
 [0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]]
all rows after 50th row and all columns till 7th coloumn for these rows:
 [[0. 0. 1. 2. 3. 4.

In [40]:
#Side note
#Not all functions require an input argument. Parantheses are written to tell Python that we are calling a function with no inputs
#For example, the ctime() function of the package time tells the current time
import time
print("Current Date and Time: ", time.ctime())

Current Date and Time:  Tue Feb  2 16:12:41 2021


In [42]:
#NumPy analyzing functions
print("Mean or average of all elements of the data array, or the average inflammation counts for all patients over all days: ",np.mean(data))
print("Max value (Max number of infammations of any patient over all days): ", np.max(data))
print("Min value (Min number of infammations of any patient over all days): ", np.min(data))
print("Standard deviation of number of infammations of all patient over all days): ", np.std(data))

Mean or average of all elements of the data array, or the average inflammation counts for all patients over all days:  6.14875
Max value (Max number of infammations of any patient over all days):  20.0
Min value (Min number of infammations of any patient over all days):  0.0
Standard deviation of number of infammations of all patient over all days):  4.613833197118566


In [83]:
#Getting the maximum inflammations of a given patient
n=0
patient_n = data[n] #Can also be used as data[0,:] which indicates to pick the 0th row and every column
#print(patient_0)
if((n+1)>10 and (n+1)<20):
    th="th"
elif((n+1)%10==1):
    th="st" 
elif((n+1)%10==2):
    th="nd" 
elif((n+1)%10==3):
    th="rd" 
else:
    th="th"
print("Maximum inflammation of ",n+1, th," patient is: ",np.max(patient_n))
#Or
print("Minimum inflammation of ",n+1,"\bst patient is: ",np.min(data[n]))
#Here \b is the regular expression telling the print pointer to go Back by one character

Maximum inflammation of  1 st  patient is:  18.0
Minimum inflammation of  1st patient is:  0.0


In [115]:
#What we need is
from IPython.display import HTML
HTML('<iframe width="800" height="400" src="https://swcarpentry.github.io/python-novice-inflammation/fig/python-operations-across-axes.png" frameborder="0" style="background:#FFFFFF;" allowfullscreen></iframe>')